export const CUSTOMER_FIELDS = {
    CHANNEL: "channel",
    CHANNEL_CUSTOMER_ID: "channel_customer_id",
    CUSTOMER_NAME: "customer_name",
    PHONE: "phone",
    CURRENT_STAGE: "current_stage",
    BUYER_INTENT: "buyer_intent",
    LEAD_SCORE: "lead_score",
    HOT_LEAD: "hot_lead",
    AI_SUMMARY: "ai_summary",
    LAST_MESSAGE: "last_message",
    MESSAGE_COUNT: "message_count",

    PRODUCT_NAME: "product_name",
    PRODUCT_SIZE: "product_size",
    PRODUCT_QTY: "product_qty",
    PRODUCT_UNIT: "product_unit",

    PENDING_PAYMENT: "pending_payment",
    PENDING_SLIP_AMOUNT: "pending_slip_amount",
    PENDING_SLIP_BANK: "pending_slip_bank",
    PENDING_SLIP_IMAGE_URL: "pending_slip_image_url",
    PENDING_SLIP_ATTACHMENT: "pending_slip_attachment",

    PIPELINES_HISTORY: "pipelines_history",
    ORDERS_HISTORY: "orders_history",

    ACTIVE_PIPELINE_ID: "active_pipeline_id",
    ACTIVE_ORDER_ID: "active_order_id",

    SALES_OWNER: "sales_owner",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
} as const;

export const CONVERSATION_FIELDS = {
    CUSTOMER: "customer",
    CHANNEL: "channel",
    EXTERNAL_MESSAGE_ID: "external_message_id",
    MESSAGE_TYPE: "message_type",
    MESSAGE: "message",
    IMAGE_URL: "image_url",
    IMAGE_ATTACHMENT: "image_attachment",
    INTENT: "intent",
    BUYER_INTENT: "buyer_intent",
    IMAGE_TYPE: "image_type",
    LEAD_SCORE: "lead_score",
    HOT_LEAD: "hot_lead",
    AI_SUMMARY: "ai_summary",
    PROCESS_STATUS: "process_status",
    ERROR_MESSAGE: "error_message",
    CREATED_AT: "created_at",
} as const;

export const PIPELINE_FIELDS = {
    CUSTOMER: "customer",
    STAGE: "stage",
    STATUS: "status",
    LEAD_SCORE: "lead_score",
    AI_SUMMARY: "ai_summary",
    SALES_OWNER: "sales_owner",
    CREATED_AT: "created_at",
    CLOSED_AT: "closed_at",
    ORDER: "order",
} as const;

export const ORDER_FIELDS = {
    ORDER_NUMBER: "order_number",
    CUSTOMER: "customer",
    PIPELINE: "pipeline",
    CHANNEL: "channel",
    EXTERNAL_ORDER_ID: "external_order_id",
    CUSTOMER_NAME: "customer_name",
    PHONE: "phone",
    ADDRESS: "address",
    PRODUCT_NAME: "product_name",
    PRODUCT_SIZE: "product_size",
    PRODUCT_UNIT: "product_unit",
    QUANTITY: "quantity",
    TOTAL_AMOUNT: "total_amount",
    PAYMENT_STATUS: "payment_status",
    PAYMENT_VERIFIED: "payment_verified",
    ORDER_STATUS: "order_status",
    SALES_OWNER: "sales_owner",
    SLIP_AMOUNT: "slip_amount",
    SLIP_BANK: "slip_bank",
    SLIP_IMAGE_URL: "slip_image_url",
    SLIP_ATTACHMENT: "slip_attachment",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    PAID_AT: "paid_at",
    PAYMENT_DUE_AT: "payment_due_at",

    MARKETPLACE_STORE_ID: "marketplace_store_id",
    MARKETPLACE_STORE_NAME: "marketplace_store_name",
    MARKETPLACE_STATUS: "marketplace_status",
    MARKETPLACE_ITEMS_JSON: "marketplace_items_json",
    MARKETPLACE_EVENT_ID: "marketplace_event_id",
    MARKETPLACE_UPDATED_AT: "marketplace_updated_at",
    CURRENCY: "currency",
    TRACKING_NUMBER: "tracking_number",
    SHIPPING_PROVIDER: "shipping_provider",
    // ฟิลด์เสริมแบบ optional: หาก Base ยังไม่มี ระบบจะ fallback ไปใช้ tracking/order status
    FULFILLMENT_STATUS: "fulfillment_status",

    // Runtime state ของ PC Engine สำหรับ Idempotency และ Recovery
    PC_INVENTORY_STATUS: "pc_inventory_status",
    PC_INVENTORY_STATE_JSON: "pc_inventory_state_json",
    PC_INVENTORY_UPDATED_AT: "pc_inventory_updated_at",

    QUOTATION_URL: "quotation_url",
    INVOICE_URL: "invoice_url",
    TAX_INVOICE_URL: "tax_invoice_url",
    TAX_FORM_URL: "tax_form_url",
    TAX_NAME: "tax_name",
    TAX_ADDRESS: "tax_address",
    TAX_ID: "tax_id",
    TAX_BRANCH: "tax_branch",
} as const;

export const ACTIVITY_FIELDS = {
    EVENT_ID: "event_id",
    CUSTOMER: "customer",
    ACTION: "action",
    OLD_VALUE: "old_value",
    NEW_VALUE: "new_value",
    CREATED_AT: "created_at",
} as const;

export const NOTIFICATION_FIELDS = {
    EVENT_ID: "event_id",
    NOTIFICATION_TYPE: "notification_type",
    CUSTOMER: "customer",
    MESSAGE: "message",
    PAYLOAD_JSON: "payload_json",
    STATUS: "status",
    ATTEMPT_COUNT: "attempt_count",
    ERROR_MESSAGE: "error_message",
    CREATED_AT: "created_at",
    SENT_AT: "sent_at",
} as const;

export const PC_PRODUCT_FIELDS = {
    SKU: "sku",
    PRODUCT_ID: "product_id",
    STYLE_CODE: "style_code",
    PRODUCT_NAME: "product_name",
    CATEGORY: "category",
    COLOR: "color",
    SIZE: "size",
    SALES_PRICE_THB: "sales_price_thb",
    STOCK_ON_HAND: "stock_on_hand",
    MIN_STOCK: "min_stock",
    TARGET_STOCK: "target_stock",
    STOCK_STATUS: "stock_status",
    RECOMMENDED_PRODUCTION_QTY: "recommended_production_qty",
    PRODUCTION_LEAD_DAYS: "production_lead_days",
    MATERIALS_JSON: "materials_json",
    ACTIVE: "active",
} as const;

export const PC_MATERIAL_FIELDS = {
    MATERIAL_SKU: "material_sku",
    MATERIAL_NAME: "material_name",
    CATEGORY: "category",
    UNIT: "unit",
    SOURCE_TYPE: "source_type",
    SUPPLIER_NAME: "supplier_name",
    SUPPLIER_COUNTRY: "supplier_country",
    LEAD_TIME_DAYS: "lead_time_days",
    STOCK_ON_HAND: "stock_on_hand",
    MIN_STOCK: "min_stock",
    TARGET_STOCK: "target_stock",
    PLANNED_REQUIREMENT: "planned_requirement",
    PROJECTED_STOCK: "projected_stock",
    SHORTAGE_QTY: "shortage_qty",
    MATERIAL_STATUS: "material_status",
    RECOMMENDED_REORDER_QTY: "recommended_reorder_qty",
    ALERT_LEVEL: "alert_level",
    ACTIVE: "active",
    NOTES: "notes",
} as const;

export const PC_PRODUCTION_FIELDS = {
    PRODUCTION_ID: "production_id",
    SOURCE_ORDER_ID: "source_order_id",
    PRODUCT_SKU: "product_sku",
    PRODUCT_NAME: "product_name",
    REASON: "reason",
    ORDER_SHORTAGE_QTY: "order_shortage_qty",
    RECOMMENDED_QTY: "recommended_qty",
    PLANNED_QTY: "planned_qty",
    ACTUAL_QTY: "actual_qty",
    MATERIAL_CHECK_STATUS: "material_check_status",
    PRODUCTION_STATUS: "production_status",
    MATERIAL_REQUIREMENT_SUMMARY: "material_requirement_summary",
    MATERIAL_RISK_SUMMARY: "material_risk_summary",
    DUE_DATE: "due_date",
    INVENTORY_POSTED: "inventory_posted",
    INVENTORY_POSTING_STATE_JSON: "inventory_posting_state_json",
    CREATED_AT: "created_at",
    COMPLETED_AT: "completed_at",
    OWNER: "owner",
    NOTES: "notes",
} as const;
