export const CUSTOMER_FIELDS = {
    CHANNEL: "channel",
    CHANNEL_CUSTOMER_ID: "channel_customer_id",
    CUSTOMER_NAME: "customer_name",
    PHONE: "phone",
    CURRENT_STAGE: "current_stage",
    BUYER_INTENT: "buyer_intent",
    LEAD_SCORE: "lead_score",
    HOT_LEAD: "hot_lead",
    AI_SUMMARY: "ai_summary",
    LAST_MESSAGE: "last_message",
    MESSAGE_COUNT: "message_count",

    PRODUCT_NAME: "product_name",
    PRODUCT_SIZE: "product_size",
    PRODUCT_QTY: "product_qty",
    PRODUCT_UNIT: "product_unit",

    PENDING_PAYMENT: "pending_payment",
    PENDING_SLIP_AMOUNT: "pending_slip_amount",
    PENDING_SLIP_BANK: "pending_slip_bank",
    PENDING_SLIP_IMAGE_URL: "pending_slip_image_url",
    PENDING_SLIP_ATTACHMENT: "pending_slip_attachment",

    PIPELINES_HISTORY: "pipelines_history",
    ORDERS_HISTORY: "orders_history",

    ACTIVE_PIPELINE_ID: "active_pipeline_id",
    ACTIVE_ORDER_ID: "active_order_id",

    SALES_OWNER: "sales_owner",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
} as const;

export const CONVERSATION_FIELDS = {
    CUSTOMER: "customer",
    CHANNEL: "channel",
    EXTERNAL_MESSAGE_ID: "external_message_id",
    MESSAGE_TYPE: "message_type",
    MESSAGE: "message",
    IMAGE_URL: "image_url",
    IMAGE_ATTACHMENT: "image_attachment",
    INTENT: "intent",
    BUYER_INTENT: "buyer_intent",
    IMAGE_TYPE: "image_type",
    LEAD_SCORE: "lead_score",
    HOT_LEAD: "hot_lead",
    AI_SUMMARY: "ai_summary",
    PROCESS_STATUS: "process_status",
    ERROR_MESSAGE: "error_message",
    CREATED_AT: "created_at",
} as const;

export const PIPELINE_FIELDS = {
    CUSTOMER: "customer",
    STAGE: "stage",
    STATUS: "status",
    LEAD_SCORE: "lead_score",
    AI_SUMMARY: "ai_summary",
    SALES_OWNER: "sales_owner",
    CREATED_AT: "created_at",
    CLOSED_AT: "closed_at",
    ORDER: "order",
} as const;

export const ORDER_FIELDS = {
    ORDER_NUMBER: "order_number",
    CUSTOMER: "customer",
    PIPELINE: "pipeline",
    CHANNEL: "channel",
    EXTERNAL_ORDER_ID: "external_order_id",
    CUSTOMER_NAME: "customer_name",
    PHONE: "phone",
    ADDRESS: "address",
    PRODUCT_NAME: "product_name",
    PRODUCT_SIZE: "product_size",
    PRODUCT_UNIT: "product_unit",
    QUANTITY: "quantity",
    TOTAL_AMOUNT: "total_amount",
    PAYMENT_STATUS: "payment_status",
    PAYMENT_VERIFIED: "payment_verified",
    ORDER_STATUS: "order_status",
    SALES_OWNER: "sales_owner",
    SLIP_AMOUNT: "slip_amount",
    SLIP_BANK: "slip_bank",
    SLIP_IMAGE_URL: "slip_image_url",
    SLIP_ATTACHMENT: "slip_attachment",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    PAID_AT: "paid_at",
    PAYMENT_DUE_AT: "payment_due_at",
} as const;

export const ACTIVITY_FIELDS = {
    EVENT_ID: "event_id",
    CUSTOMER: "customer",
    ACTION: "action",
    OLD_VALUE: "old_value",
    NEW_VALUE: "new_value",
    CREATED_AT: "created_at",
} as const;

export const NOTIFICATION_FIELDS = {
    EVENT_ID: "event_id",
    NOTIFICATION_TYPE: "notification_type",
    CUSTOMER: "customer",
    MESSAGE: "message",
    PAYLOAD_JSON: "payload_json",
    STATUS: "status",
    ATTEMPT_COUNT: "attempt_count",
    ERROR_MESSAGE: "error_message",
    CREATED_AT: "created_at",
    SENT_AT: "sent_at",
} as const;
